### ISSUE TITLE
Tensor Discrepancy 

### ISSUE THREAD

**Issue by nicholas-leonard** [torch/cutorch#147]
Hi,

When we create an empty torch.CudaTensor, it gets initialized with an empty storage:
```lua
x = torch.CudaTensor()
print(x:storage())
[torch.CudaStorage of size 0]
```

However, when we create an empty torch.FloatTensor (or any other Tensor AFAIK), it gets initialized without a storage:
```lua
x = torch.FloatTensor()
print(x:storage())
nil
```

**Comment by dominikgrewe** [comment]
Yes, this is a recent change introduced by #136
I flagged it at the time, but we still went ahead because we didn't think it would cause any problems. Do you have a case where this is a problem?

**Comment by nicholas-leonard** [comment]
Yeah but I fixed it for my case (I was casting a structure of modules to a type while preserving storage sharing). Had to scratch my head for a while to find the bug though. 

So its a corner case. I am guessing this change wont affect most users. Just wanted to make sure there was a reason for the discrepancy. Thanks.

**Comment by nicholas-leonard** [comment]
Actually, the fact that `torch.pointer(param:storage():data())` of empty torch.CudaTensors causes me trouble because the pointer is zero. But I guess I can assume that pointers to zero are null? Its weird because I am using the pointer to determine if the storages are shared. So I guess it is safe to assume that zero-sized storages cannot be shared right?

**Comment by nicholas-leonard** [comment]
Ah but they can be shared...

**Comment by soumith** [comment]
I think you can use tonumber(param:storage():cdata()) to determine sharing.

**Comment by nicholas-leonard** [comment]
```lua
th> a = torch.CudaTensor()
th> print(tonumber(a:storage():cdata()))
nil
```

**Comment by soumith** [comment]
tonumber(ffi.cast('intptr_t', param:storage():cdata()))

**Comment by nicholas-leonard** [comment]
Yeah that works. Only problem is that it introduces ffi as a dependency. Can I use it on a smartphone? Anyway, for now I am choosing to assume all empty storages (zero pointers) aren't shared. Thanks though.

**Comment by dominikgrewe** [comment]
The more I think about it, the more I think we should fix this. It's just going to cause confusion if a CudaTensor behaves differently from a regular Torch Tensor. Calling `data` on an empty tensor doesn't return `nil` any more, same for `storage`. If we want API parity between Torch and cutorch, then this needs to be fixed.
The reason an empty CudaTensor has a storage, is so that it can be assigned to a specific device (only storages have a device ID). Either we give tensors a device ID too or we change Torch so that empty tensor of any type have storages. The latter will probably break lots of people's code though. Wdyt?

**Comment by soumith** [comment]
How about we make the entire behavior of auto-mode opt-in, including the behavior changed here in libTHC statically. We do have some internal tests breaking.

**Comment by adamlerer** [comment]
@dominikgrewe you're right, I have to fix the inconsistencies with regular torch tensors. This change is also going to break serialization.

I think I'm going to back out these changes and take some time to rework it.

**Comment by soumith** [comment]
reverted both the diffs! thanks @adamlerer

**Comment by adamlerer** [comment]
@soumith @dominikgrewe I would like to rework auto-mode, avoiding inconsistencies with Torch (and serialization inconsistencies). I'm willing to sacrifice a bit of the auto-mode functionality to avoid the rat's nest of corner cases. I propose:

* Empty tensors don't have a storage; they cannot be assigned to a device.
* `Tensor:cudaOn(device)` and `Tensor:cloneOn(device)` only works on non-empty tensors; `CudaTensorOn(device)` could perhaps default to a size-1 tensor.
* `Module:cudaOn(device)` will initialize empty tensors to size 1. In all the cases I know of, they get resized anyway on the first pass so it doesn't matter.

With these changes, I no longer require `Storage`s to have a `device` field; I could keep calling `cudaGetDevice()` on the data pointer. The problem with calling `cudaGetDevice(dat)` is that I measured 700ns per `cudaGetDevice(data)` call, which we're already calling multiple times inside of `checkGPU()`. Opinions?

If we keep the `device` field, that leaves what to do about [de]serializing it. Right now, deserialization is implicitly always onto the current device. If I add a `device` field, I can choose to serialize it or not. If I serialize it, then I can restore multi-GPU models properly, but you better deserialize onto a machine with the same number of devices.

**Comment by dominikgrewe** [comment]
I think I prefer an explicit `device` field in both `Tensor` and `Storage`. Using a size-1 tensor for "empty" tensors in `Module:cudaOn()` may again cause issues because you can't distinguish between a tensor that hasn't been given a size yet and one that's been given a size of 1. This is probably less of an issue than what we had before, but it still doesn't feel very nice.
Having a `device` field means, of course, that we have some extra book-keeping to do. But I believe those changes should all be very localized (namely in THCTensor.c and THCStorage.c).

Re serialization: I think the `device` field should be serialized and multi-GPU models should be re-stored properly. If that's not possible we could either fail or have a warning saying that the some module or tensor will be re-stored on the wrong device.
