### ISSUE TITLE
:addcdiv() and :addcmul() do not preserve shape

### ISSUE THREAD

**Issue by fidlej** [torch/cutorch#221]
The :addcdiv() and :addcmul() don't preserve the existing tensor shape,
when used on a CudaTensor.

The following example shows the output size,
when a FloatTensor or a CudaTensor is used:

    torch.FloatTensor	output size:
     5
     2
    [torch.LongStorage of size 2]

    torch.CudaTensor	output size:
     10
    [torch.LongStorage of size 1]

The example:

    require 'cutorch'
    require 'cunn'

    local nY = 5
    local nX = 2
    for _, wantedType in ipairs({'torch.FloatTensor', 'torch.CudaTensor'}) do
      local input = torch.randn(nY * nX):type(wantedType)

      local output = input.new(nY, nX):zero()
      output:addcdiv(input, input)
      print(wantedType, "output size:", output:size())
    end

The nn.CDivTable() is then returning a wrong gradInput[2] shape.
I guess, `THCudaTensor_resizeAs(state, self_, src1);` should not be used
for the add*() methods.

**Comment by dominikgrewe** [comment]
So it seems that there are two issues here:

1) cutorch changes the size of the output tensor even though it has the right number of elements. This behaviour is different from Torch and should be fixed for consistency.

2) When the output tensor is also an input tensor, as in the example above, we shouldn't resize it. Instead we should check that is has the right size, otherwise we may use uninitialized data.

**Comment by dominikgrewe** [comment]
Actually the first point isn't quite true. It only changes the size of the output tensor if it is not used as an input. This is consistent with Torch.
