### ISSUE TITLE
Error loading module 'cutorch' on OS X Yosemite 10.10.4

### ISSUE THREAD

**Issue by ksarma** [torch/cutorch#243]
Hi folks,

I'm having trouble with cutorch on OS X 10.10.4 (with CUDA 7.5 installed). Regular torch works fine, as do the CUDA samples from NVIDIA.

Here is the error I am getting (replaced my user directory with ~ for brevity):

```
th> require 'cutorch';
~/torch/install/share/lua/5.1/trepl/init.lua:363: loop or previous error loading module 'cutorch'
stack traceback:
	[C]: in function 'error'
	~/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
	[string "require 'cutorch';"]:1: in main chunk
	[C]: in function 'xpcall'
	~/torch/install/share/lua/5.1/trepl/init.lua:648: in function 'repl'
	~/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x010f63e780
```

Here is the result of luajit -lcutorch

```
$ luajit -lcutorch
luajit: ~/torch/install/share/lua/5.1/cutorch/init.lua:2: cannot load '~/torch/install/lib/lua/5.1/libcutorch.so'
stack traceback:
	[C]: in function 'require'
	~/torch/install/share/lua/5.1/cutorch/init.lua:2: in main chunk
	[C]: at 0x010f1b0d00
	[C]: at 0x010f182780
```

(the file ~/torch/install/lib/lua/5.1/libcutorch.so does exist with size 578716)

I looked through the existing issues but didn't quite find the same thing; hopefully I'm not missing something stupid. Here's one caveat that I think might be causing the problem, but I'm not really expert enough to know for sure. The latest version of XCode has a version of clang that is not supported by CUDA. So, I have to use xcode 6.2 when I am installing cutorch since I think that is the last version that still has clang 6. However, I am not able to compile regular torch using xcode 6.2 -- I need the latest version of xcode (7.0) to make that work. So I am first installing torch with the latest xcode, then using xcode-select to switch back to xcode 6.2 to install cutorch. I am not sure if that is resulting in incompatible libraries or something. Let me know if it would be helpful if I pasted in the error I get when trying to compile regular torch with xcode 6.2 or if there's anything else I should try!

Thanks!

**Comment by zdb26** [comment]
I met the same problem, and I'v also guessed that the reason is I built torch7 and cutorch with different version Xcode.

But, I found that when I try to "nm ~/torch/install/lib/lua/5.1/libcutorch.so", there is a error message. That is to say, although the file exists, but is not valid.

I googled the problem and found that someone seems to solve this by downgrade the cmake to 2.8.11, so I tried. This time, a libcutorch.so file with different size is generated, and is valid for "nm". But, what a sad, the error message "init.lua:2: cannot load '~/torch/install/lib/lua/5.1/libcutorch.so'" also there!

So, I have not solved this problem yet!

**Comment by zdb26** [comment]
Great! I solved by this:
0, My env is: OSX10.10，command-line-tools-for-Yosemite(without a entire Xcode installed), CUDA 7.5
1,  install torch7 with ezinstall only one-line-script method, but not the method on torch's page
2,  make sure that Xcode-select -p point to the /Library/Developer/CommandLineTools, but not a path in Xcode.app
3, After install the torch7, I install the cmake-2.8.11, and fix the path by adding "export PATH="/Application/CMake-2.8.11.app/Contents/bin:$PATH"". Then, install the cutorch with luarockt

Then, it works!

**Comment by DougFirErickson** [comment]
Here is a solution that worked for me on OS X 10.9:
-Uninstall torch and CUDA Toolkit 7.5
-Ensure CMake is current with `brew install --upgrade cmake`
-Install CUDA 7.0 from [here](https://developer.nvidia.com/cuda-toolkit-70)
-Follow the CUDA 7.0 instructions [here](http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-mac-os-x/#axzz49NZTipYP) to install Xcode command-line tools and add CUDA to the system path (I added it to ~/.bash_profile)
-Install torch as described on the official website. Check for errors in linking to CUDA. Add the `torch activate` path noted at the end of the installation process to the system path.

Do `th` and check if `require 'cutorch'` works. If not, then:
-Do `luarocks install findcuda` so that build files correctly locate CUDA
-Reinstall CUDA libraries with `luarocks install cutorch` and `luarocks install cunn` and `luarocks install cudnn` and any other CUDA libraries you'd like, which are listed [here](https://github.com/torch/torch7/wiki/Cheatsheet#newbies).

Everything should work. I think the issue may be with compatibility between OS X 10.9 and CUDA 7.5. I would need to do more testing to confirm this.

**Comment by ksarma** [comment]
I'm now on 10.11.4 with the latest xcode and CUDA 7.5.27 -- cutorch and cunn now seem to just work (or at least, they can be imported and cunn.testcuda() only gives 10 errors)

Happily CUDA 7.5.27 supports the latest clang, which likely accounts for why it works now.

**Comment by DougFirErickson** [comment]
I had torch working with both CUDA 7.0 and 7.5 after following the above procedure on OS X 10.9.
