### ISSUE TITLE
topk, sort problem

### ISSUE THREAD

**Issue by WenjieLuo** [torch/cutorch#350]
Hi, I have this script on topk function, which turns out to be very slow(takes a long to finish after the print..), but it's ok with sort function. So I'm guessing there is something wrong with topk function? Does anybody know what might be the problem?

require 'cutorch'
x = torch.CudaTensor(20,1000,1000):zero()
y,i = x:topk(3,1)
print(#y)
it gives "74.44s user 15.60s system 99% cpu 1:30.23 total"
using x:sort(1), it gives: "3.37s user 1.60s system 93% cpu 5.334 total"

I'm on a Titan X
Thanks!

**Comment by wickedfoo** [comment]
I just ran it and didn't get anywhere near the same numbers:

0.26user 1.18system 0:05.42elapsed 26%CPU (0avgtext+0avgdata 443860maxresident)

also on Titan X.

This is probably also the worst-case scenario for the existing top-k (the dimension is outermost, the size of that dimension is small, so it is evaluating top-k for 1 million separate small slices). Since it is filled with zeros, it is similarly a worst case for radix selection (since 8 passes are made over each of the 1 million slices).

I have a GPU heap implementation that is much faster for small k (<= 512) working internally that doesn't require multiple passes that should make this much faster, and is not sensitive to bad radix selection cases. I think bad performance here is expected, but it shouldn't be as bad as you saw it (74 seconds).

**Comment by soumith** [comment]
@WenjieLuo see if it's the same when you run it a second time. I suspect that the first time when you ran topk, cutorch probably JIT-compiled itself or something.

**Comment by WenjieLuo** [comment]
@wickedfoo @soumith Thanks for your replies.
Interestingly I don't have the issue while running in interactive mode, but only while running as a script. The topk function finished fast and I can see the output of print(#y), but it took a lot of time to finish/exit the script(doing some cleaning work I assume?), while sort function is good. Do you have any ideas on this behavior? Would it be a problem for topk in cleaning memory or something?

**Comment by WenjieLuo** [comment]
Here is a simple example showing 'sort' might have a problem:

require 'cutorch'
x = torch.rand(11061,303,50):cuda()
v,i = x:sort(1)
print(v[{{1,15},200,30}])

output:
 0.9987
 0.9988
 0.9989
 0.9990
 0.9991
 0.9994
 0.9997
 0.9997
 0.9998
 0.9999
 0.0000
 0.0001
 0.0001
 0.0002
 0.0002

any ideas?

**Comment by wickedfoo** [comment]
@WenjieLuo that sort issue is the same as https://github.com/torch/cutorch/issues/339, fix will be coming soon.

Also, note that top-k or sort for the outermost dimension or any dimension which is non-contiguous will always be slow.

**Comment by WenjieLuo** [comment]
@wickedfoo does #339 effect topk? i.e. is x = torch.CudaTensor(1000,10,3000) x:topk(10,3) guaranteed work?

**Comment by wickedfoo** [comment]
@WenjieLuo only if the sort argument to topk is true should that be affected I think. Otherwise topk provides no guarantee of sorting its results

**Comment by wickedfoo** [comment]
#339 is fixed now
