### ISSUE TITLE
Multi Threaded Code is running Slow

### ISSUE THREAD

**Issue by jbansal** [torch/cutorch#381]
Hi All,
I am using 'thread' to create multi threading for Multi GPU support. I am loading my model to each thread while creating threads.
After creating threads, I am adding my data to each thread using thread:addJob(callback, endCallback ) and then returning gradients of the model of that particular GPU model (after doing model:forward and model:backward) from the callback function to endcallback function, where I am updating my main models parameters.

Now Issue is that when I use threading, it is taking Around 8-10 seconds for 1 batch with 128 images to add in queue and return to take another batch data. I found that the reason for this is queue method where data is saved into memoryFile and the reading from memory file. Is there any faster way to optimize this as I am passing huge data as return of callback (gradients of model after backward call).
Due to above, this threading code using 4 GPUs is running slower than single GPU code.

Is there any way to optimize my code to use multi GPU to train machine (using threading) faster then using single GPU?

Regards,
Jitendra Bansal

**Comment by albanD** [comment]
Hi

You may want to take a look at the serialization in torch threads https://github.com/torch/threads#threadsserializationpkgname
In particular, you can use `threads.sharedserialize` so that Tensors and tds tables will be shared between threads (and not serialized in memory files as your see right now).

**Comment by jbansal** [comment]
Hi albanD,
Thanks for your quick reply.
I tried threadserialization and it works when we are using only 1 GPU for all the threads.
When I use multiple GPU with threadserialization, I got following error:


/usr/local/share/lua/5.1/threads/threads.lua:264:
[thread 2 callback] /usr/local/share/lua/5.1/nn/THNN.lua:1091: Assertion `THCudaTensor_checkGPU(state, 6, input, output, weight, bias, columns, ones)' failed.  at /tmp/luarocks_cunn-scm-1-2908/cunn/lib/THCUNN/SpatialConvolutionMM.cu:8
stack traceback:
        /usr/local/share/lua/5.1/fb/util/error.lua:76: in function </usr/local/share/lua/5.1/fb/util/error.lua:72>
        [C]: in function 'v'
        /usr/local/share/lua/5.1/nn/THNN.lua:1091: in function 'SpatialConvolutionMM_updateOutput'
        /usr/local/share/lua/5.1/nn/SpatialConvolution.lua:104: in function 'updateOutput'
        /usr/local/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
        /usr/local/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        Load_CropImages.lua:132: in function 'TrainBatchData'
        thread_exam_MultiGPU.lua:221: in function <thread_exam_MultiGPU.lua:211>
        [C]: in function 'real_xpcall'
        /usr/local/share/lua/5.1/fb/util/error.lua:85: in function 'xpcall'
        /usr/local/share/lua/5.1/threads/threads.lua:231: in function 'callback'
        /usr/local/share/lua/5.1/threads/queue.lua:65: in function </usr/local/share/lua/5.1/threads/queue.lua:41>
        [C]: in function 'real_xpcall'
        /usr/local/share/lua/5.1/fb/util/error.lua:85: in function 'pcall'
        /usr/local/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
        [string "  local Queue = require 'threads.queue'..."]:15: in main chunk


Regards,
Jitendra Bansal

**Comment by albanD** [comment]
First, I am not sure if you know about [DataParallelTable](https://github.com/torch/cunn/blob/master/doc/cunnmodules.md#dataparalleltable) from cunn, It may be doing exactly what you are trying to implement.

The error you get is because the input of one of your model in not on the correct GPU.
The model and the input you forward in it MUST be on the same GPU otherwise you will have the error above.

In any case, if you have more questions, we should move this conversation to the google group https://groups.google.com/forum/#!forum/torch7 . The github issues are used only for bugs.

**Comment by jbansal** [comment]
Hi AlbanD,
By using DataparallelTable didn't help me. It makes my code slower than single GPU.
I have posted my query on googlegroup.
https://groups.google.com/forum/#!topic/torch7/xJjs_QTHhXA

Regards,
jitendra Bansal
